language: r
cache: packages
warnings_are_errors: false

apt_packages:
  # git2.h required by gert (probably dependency: testthat -> usethis)
  - libgit2-dev

r_packages:
  - covr

r_github_packages: xrobin/mnist

after_success:
  - Rscript -e 'library(covr); codecov()'
